FROM node:16.15.1-alpine

WORKDIR /usr/src/app
COPY package*.json ./
COPY yarn.lock ./
RUN yarn
RUN yarn global add pm2

COPY ./ ./
RUN yarn build

EXPOSE 3000

CMD [ "pm2-runtime", "start", "npm", "--", "run", "start:dev" ]